/* 
 * Strava API v3
 *
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * OpenAPI spec version: 3.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Strava.Client.SwaggerDateConverter;

namespace Strava.Model
{
    /// <summary>
    /// An enumeration of the sport types an activity may have. Distinct from ActivityType in that it has new types (e.g. MountainBikeRide)
    /// </summary>
    /// <value>An enumeration of the sport types an activity may have. Distinct from ActivityType in that it has new types (e.g. MountainBikeRide)</value>
    [JsonConverter(typeof(StringEnumConverter))]
        public enum SportType
    {
        /// <summary>
        /// Enum AlpineSki for value: AlpineSki
        /// </summary>
        [EnumMember(Value = "AlpineSki")]
        AlpineSki = 1,
        /// <summary>
        /// Enum BackcountrySki for value: BackcountrySki
        /// </summary>
        [EnumMember(Value = "BackcountrySki")]
        BackcountrySki = 2,
        /// <summary>
        /// Enum Badminton for value: Badminton
        /// </summary>
        [EnumMember(Value = "Badminton")]
        Badminton = 3,
        /// <summary>
        /// Enum Canoeing for value: Canoeing
        /// </summary>
        [EnumMember(Value = "Canoeing")]
        Canoeing = 4,
        /// <summary>
        /// Enum Crossfit for value: Crossfit
        /// </summary>
        [EnumMember(Value = "Crossfit")]
        Crossfit = 5,
        /// <summary>
        /// Enum EBikeRide for value: EBikeRide
        /// </summary>
        [EnumMember(Value = "EBikeRide")]
        EBikeRide = 6,
        /// <summary>
        /// Enum Elliptical for value: Elliptical
        /// </summary>
        [EnumMember(Value = "Elliptical")]
        Elliptical = 7,
        /// <summary>
        /// Enum EMountainBikeRide for value: EMountainBikeRide
        /// </summary>
        [EnumMember(Value = "EMountainBikeRide")]
        EMountainBikeRide = 8,
        /// <summary>
        /// Enum Golf for value: Golf
        /// </summary>
        [EnumMember(Value = "Golf")]
        Golf = 9,
        /// <summary>
        /// Enum GravelRide for value: GravelRide
        /// </summary>
        [EnumMember(Value = "GravelRide")]
        GravelRide = 10,
        /// <summary>
        /// Enum Handcycle for value: Handcycle
        /// </summary>
        [EnumMember(Value = "Handcycle")]
        Handcycle = 11,
        /// <summary>
        /// Enum HighIntensityIntervalTraining for value: HighIntensityIntervalTraining
        /// </summary>
        [EnumMember(Value = "HighIntensityIntervalTraining")]
        HighIntensityIntervalTraining = 12,
        /// <summary>
        /// Enum Hike for value: Hike
        /// </summary>
        [EnumMember(Value = "Hike")]
        Hike = 13,
        /// <summary>
        /// Enum IceSkate for value: IceSkate
        /// </summary>
        [EnumMember(Value = "IceSkate")]
        IceSkate = 14,
        /// <summary>
        /// Enum InlineSkate for value: InlineSkate
        /// </summary>
        [EnumMember(Value = "InlineSkate")]
        InlineSkate = 15,
        /// <summary>
        /// Enum Kayaking for value: Kayaking
        /// </summary>
        [EnumMember(Value = "Kayaking")]
        Kayaking = 16,
        /// <summary>
        /// Enum Kitesurf for value: Kitesurf
        /// </summary>
        [EnumMember(Value = "Kitesurf")]
        Kitesurf = 17,
        /// <summary>
        /// Enum MountainBikeRide for value: MountainBikeRide
        /// </summary>
        [EnumMember(Value = "MountainBikeRide")]
        MountainBikeRide = 18,
        /// <summary>
        /// Enum NordicSki for value: NordicSki
        /// </summary>
        [EnumMember(Value = "NordicSki")]
        NordicSki = 19,
        /// <summary>
        /// Enum Pickleball for value: Pickleball
        /// </summary>
        [EnumMember(Value = "Pickleball")]
        Pickleball = 20,
        /// <summary>
        /// Enum Pilates for value: Pilates
        /// </summary>
        [EnumMember(Value = "Pilates")]
        Pilates = 21,
        /// <summary>
        /// Enum Racquetball for value: Racquetball
        /// </summary>
        [EnumMember(Value = "Racquetball")]
        Racquetball = 22,
        /// <summary>
        /// Enum Ride for value: Ride
        /// </summary>
        [EnumMember(Value = "Ride")]
        Ride = 23,
        /// <summary>
        /// Enum RockClimbing for value: RockClimbing
        /// </summary>
        [EnumMember(Value = "RockClimbing")]
        RockClimbing = 24,
        /// <summary>
        /// Enum RollerSki for value: RollerSki
        /// </summary>
        [EnumMember(Value = "RollerSki")]
        RollerSki = 25,
        /// <summary>
        /// Enum Rowing for value: Rowing
        /// </summary>
        [EnumMember(Value = "Rowing")]
        Rowing = 26,
        /// <summary>
        /// Enum Run for value: Run
        /// </summary>
        [EnumMember(Value = "Run")]
        Run = 27,
        /// <summary>
        /// Enum Sail for value: Sail
        /// </summary>
        [EnumMember(Value = "Sail")]
        Sail = 28,
        /// <summary>
        /// Enum Skateboard for value: Skateboard
        /// </summary>
        [EnumMember(Value = "Skateboard")]
        Skateboard = 29,
        /// <summary>
        /// Enum Snowboard for value: Snowboard
        /// </summary>
        [EnumMember(Value = "Snowboard")]
        Snowboard = 30,
        /// <summary>
        /// Enum Snowshoe for value: Snowshoe
        /// </summary>
        [EnumMember(Value = "Snowshoe")]
        Snowshoe = 31,
        /// <summary>
        /// Enum Soccer for value: Soccer
        /// </summary>
        [EnumMember(Value = "Soccer")]
        Soccer = 32,
        /// <summary>
        /// Enum Squash for value: Squash
        /// </summary>
        [EnumMember(Value = "Squash")]
        Squash = 33,
        /// <summary>
        /// Enum StairStepper for value: StairStepper
        /// </summary>
        [EnumMember(Value = "StairStepper")]
        StairStepper = 34,
        /// <summary>
        /// Enum StandUpPaddling for value: StandUpPaddling
        /// </summary>
        [EnumMember(Value = "StandUpPaddling")]
        StandUpPaddling = 35,
        /// <summary>
        /// Enum Surfing for value: Surfing
        /// </summary>
        [EnumMember(Value = "Surfing")]
        Surfing = 36,
        /// <summary>
        /// Enum Swim for value: Swim
        /// </summary>
        [EnumMember(Value = "Swim")]
        Swim = 37,
        /// <summary>
        /// Enum TableTennis for value: TableTennis
        /// </summary>
        [EnumMember(Value = "TableTennis")]
        TableTennis = 38,
        /// <summary>
        /// Enum Tennis for value: Tennis
        /// </summary>
        [EnumMember(Value = "Tennis")]
        Tennis = 39,
        /// <summary>
        /// Enum TrailRun for value: TrailRun
        /// </summary>
        [EnumMember(Value = "TrailRun")]
        TrailRun = 40,
        /// <summary>
        /// Enum Velomobile for value: Velomobile
        /// </summary>
        [EnumMember(Value = "Velomobile")]
        Velomobile = 41,
        /// <summary>
        /// Enum VirtualRide for value: VirtualRide
        /// </summary>
        [EnumMember(Value = "VirtualRide")]
        VirtualRide = 42,
        /// <summary>
        /// Enum VirtualRow for value: VirtualRow
        /// </summary>
        [EnumMember(Value = "VirtualRow")]
        VirtualRow = 43,
        /// <summary>
        /// Enum VirtualRun for value: VirtualRun
        /// </summary>
        [EnumMember(Value = "VirtualRun")]
        VirtualRun = 44,
        /// <summary>
        /// Enum Walk for value: Walk
        /// </summary>
        [EnumMember(Value = "Walk")]
        Walk = 45,
        /// <summary>
        /// Enum WeightTraining for value: WeightTraining
        /// </summary>
        [EnumMember(Value = "WeightTraining")]
        WeightTraining = 46,
        /// <summary>
        /// Enum Wheelchair for value: Wheelchair
        /// </summary>
        [EnumMember(Value = "Wheelchair")]
        Wheelchair = 47,
        /// <summary>
        /// Enum Windsurf for value: Windsurf
        /// </summary>
        [EnumMember(Value = "Windsurf")]
        Windsurf = 48,
        /// <summary>
        /// Enum Workout for value: Workout
        /// </summary>
        [EnumMember(Value = "Workout")]
        Workout = 49,
        /// <summary>
        /// Enum Yoga for value: Yoga
        /// </summary>
        [EnumMember(Value = "Yoga")]
        Yoga = 50    }
}
