name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

env:
  CI: true
  PNPM_CACHE_FOLDER: .pnpm-store
  PUBLIC_MAPTILER_KEY: ${{secrets.MAPTILER_KEY}}

# cancel in-progress runs on new commits to same PR (gitub.event.number)
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: Install dependencies in Svelte subfolder
        run: pnpm install
        working-directory: Svelte

      - name: Make envfile
        run: |
          echo "PUBLIC_MAPTILER_KEY=${PUBLIC_MAPTILER_KEY}" > .env
        working-directory: Svelte

      - name: Build in Svelte subfolder
        run: pnpm run build
        working-directory: Svelte

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_THANKFUL_GROUND_0E9AC7C03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "Svelte" # App source code path
          api_location: "Api" # Api source code path - optional
          output_location: "Svelte/build/static" # Built app content directory - optional
          skip_api_build: true # needed when we set CUSTOM_BUILD_COMMAND
          skip_app_build: true
          ###### End of Repository/Build Configurations ######
    outputs:
      preview_url: ${{ steps.builddeploy.outputs.static_web_app_url }}

  test:
    needs: build_and_deploy_job
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && !github.event.pull_request.head.repo.fork && github.event.action != 'closed')
    name: Run E2E Tests
    timeout-minutes: 10
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Svelte
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18.x"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Make envfile
        run: |
          echo "PUBLIC_MAPTILER_KEY=${PUBLIC_MAPTILER_KEY}" > .env
      - name: Install Playwright
        run: npx playwright install chromium --with-deps
      - name: Run Playwright tests
        run: pnpm test
        env:
          PLAYWRIGHT_TEST_BASE_URL: ${{ needs.build_and_deploy_job.outputs.preview_url }}

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_THANKFUL_GROUND_0E9AC7C03 }}
          action: "close"
